#!/bin/bash

echo "📱 GUIA PARA REVERTER VERSÃO DO macOS"
echo "======================================"
echo ""

# Cores
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

# Verificar versão atual
current_version=$(sw_vers -productVersion)
echo -e "${BLUE}Versão atual do macOS: ${current_version}${NC}"
echo ""

echo -e "${RED}⚠️  ATENÇÃO: REVERTER O macOS É UM PROCESSO COMPLEXO E ARRISCADO${NC}"
echo "================================================================"
echo ""
echo "📋 PRÉ-REQUISITOS OBRIGATÓRIOS:"
echo "==============================="
echo ""
echo "1. ✅ BACKUP COMPLETO (Time Machine ou similar)"
echo "   - TODOS os seus arquivos devem estar em backup"
echo "   - Verifique se o backup está atualizado"
echo ""
echo "2. ✅ BACKUP DO SISTEMA ATUAL"
echo "   - Crie um backup do sistema antes de prosseguir"
echo "   - Use Time Machine ou ferramenta similar"
echo ""
echo "3. ✅ INSTALADOR DA VERSÃO ANTERIOR"
echo "   - Você precisa do instalador do macOS anterior"
echo "   - Baixe do App Store ou use outro método"
echo ""
echo "4. ⚠️  PERDA DE DADOS"
echo "   - Você PERDERÁ todos os dados não backupados"
echo "   - Aplicativos podem precisar ser reinstalados"
echo ""
echo "5. ⚠️  INCOMPATIBILIDADES"
echo "   - Alguns apps podem não funcionar na versão antiga"
echo "   - Arquivos criados na versão nova podem não abrir"
echo ""

echo -e "${YELLOW}📖 MÉTODOS PARA REVERTER:${NC}"
echo "======================"
echo ""
echo "MÉTODO 1: REINSTALAÇÃO LIMPA (RECOMENDADO)"
echo "-------------------------------------------"
echo "1. Faça backup completo com Time Machine"
echo "2. Baixe o instalador do macOS anterior:"
echo "   - macOS Sonoma (14.x): https://apps.apple.com/app/id6450717509"
echo "   - macOS Ventura (13.x): https://apps.apple.com/app/id1638787999"
echo "   - macOS Monterey (12.x): https://apps.apple.com/app/id1576738298"
echo ""
echo "3. Crie um USB bootável:"
echo "   sudo /Applications/Install\\ macOS\\ [VERSÃO].app/Contents/Resources/createinstallmedia --volume /Volumes/[NOME_USB]"
echo ""
echo "4. Reinicie segurando Option (⌥)"
echo "5. Selecione o USB bootável"
echo "6. Use Disk Utility para APAGAR o disco"
echo "7. Instale o macOS anterior"
echo "8. Restaure do Time Machine"
echo ""

echo "MÉTODO 2: REINSTALAÇÃO SOBRE A VERSÃO ATUAL (NÃO RECOMENDADO)"
echo "-------------------------------------------------------------"
echo "⚠️  Este método pode causar problemas de estabilidade"
echo "1. Baixe o instalador do macOS anterior"
echo "2. Execute o instalador"
echo "3. Ele tentará instalar sobre a versão atual"
echo "4. Pode não funcionar corretamente"
echo ""

echo "MÉTODO 3: RESTAURAÇÃO DO TIME MACHINE"
echo "-------------------------------------"
echo "1. Se você tem backup do Time Machine da versão anterior:"
echo "2. Reinicie segurando Command (⌘) + R"
echo "3. Selecione 'Restaurar do Time Machine Backup'"
echo "4. Escolha o backup da versão anterior"
echo "5. Aguarde a restauração completa"
echo ""

echo -e "${RED}🚨 RISCOS E LIMITAÇÕES:${NC}"
echo "======================"
echo ""
echo "1. ⚠️  PERDA DE DADOS:"
echo "   - Todos os dados não backupados serão perdidos"
echo "   - Aplicativos precisarão ser reinstalados"
echo ""
echo "2. ⚠️  INCOMPATIBILIDADE:"
echo "   - Apps modernos podem não funcionar"
echo "   - Arquivos criados na versão nova podem não abrir"
echo ""
echo "3. ⚠️  SEGURANÇA:"
echo "   - Versões antigas têm menos atualizações de segurança"
echo "   - Vulnerabilidades conhecidas podem não ser corrigidas"
echo ""
echo "4. ⚠️  HARDWARE:"
echo "   - Alguns Macs novos não suportam versões antigas"
echo "   - Verifique compatibilidade antes"
echo ""

echo -e "${GREEN}💡 ALTERNATIVAS ANTES DE REVERTER:${NC}"
echo "================================"
echo ""
echo "Antes de reverter, tente estas soluções:"
echo ""
echo "1. Reduzir transparências:"
echo "   ./reduce_transparency.sh"
echo ""
echo "2. Otimizar sistema:"
echo "   make optimize-heating"
echo ""
echo "3. Limpar caches e arquivos temporários:"
echo "   make organize"
echo ""
echo "4. Verificar processos pesados:"
echo "   make diagnose-heating"
echo ""
echo "5. Desativar recursos desnecessários:"
echo "   - Desative Siri se não usar"
echo "   - Desative Handoff/Continuity"
echo "   - Reduza animações"
echo ""

echo ""
echo "📞 VERIFICAR COMPATIBILIDADE:"
echo "============================"
echo ""
echo "Para verificar se seu Mac suporta versões anteriores:"
echo "1. Acesse: https://everymac.com"
echo "2. Procure pelo modelo do seu Mac"
echo "3. Veja quais versões do macOS são suportadas"
echo ""

echo -e "${YELLOW}❓ DESEJA CONTINUAR?${NC}"
echo "=================="
echo ""
echo "Este é um processo IRREVERSÍVEL sem backup adequado."
echo "Tem certeza que deseja prosseguir? (digite 'SIM' para continuar)"
read -r confirm

if [[ "$confirm" != "SIM" ]]; then
    echo ""
    echo "Operação cancelada."
    echo "Recomendamos tentar as alternativas primeiro."
    exit 0
fi

echo ""
echo -e "${RED}⚠️  ÚLTIMA CHANCE!${NC}"
echo "=================="
echo ""
echo "Você fez backup completo? (s/N)"
read -r backup_confirm

if [[ ! "$backup_confirm" =~ ^[Ss]$ ]]; then
    echo ""
    echo "Operação cancelada por segurança."
    echo "Faça backup antes de continuar."
    exit 1
fi

echo ""
echo "📋 PRÓXIMOS PASSOS:"
echo "=================="
echo ""
echo "1. Baixe o instalador do macOS anterior"
echo "2. Crie USB bootável (se necessário)"
echo "3. Reinicie e instale a versão anterior"
echo "4. Restaure seus dados do backup"
echo ""
echo "Para mais informações detalhadas, consulte:"
echo "https://support.apple.com/pt-br/guide/mac-help/mchlp1599/mac"
echo ""

